### ISSUE TITLE
Some problem with the `listings` package?

### ISSUE THREAD

**Issue by catalin-hritcu** [dmwit/pulp#5]
I'm getting the following error message:
```
./main.tex:257-9:  (../../../pub/plugin/examples/RedBlack/redblack.v
409-?: For some reason, the log-file parser noticed an extra 'close file' marker here.
	It's possible that the filenames and line numbers reported near this are wrong.
	This is likely a bug -- you should report it and include your log file!
```
when adding the following line in a tex file:
```
\lstinputlisting[language=SSR,linerange={tree}]{../../../pub/plugin/examples/RedBlack/redblack.v}
```
Included the log file on gist: 
https://gist.github.com/catalin-hritcu/710dc63725be9f56aa7c

**Comment by catalin-hritcu** [comment]
Is there any good way to suppress this kind of pulp warnings. They are annoying after a while.

**Comment by dmwit** [comment]
Yep, the `close` atom is true for these messages. So adding `& !close` to your .pulp file should prevent them.

Thanks for the report, by the way. I do plan to look into it.

**Comment by catalin-hritcu** [comment]
Thanks for the hint, it does help. There is still this part that I still have to "grep -v" for the moment:

./main.tex:291-9: (../../../pub/plugin/examples/RedBlack/redblack.v
?-57: (../../../pub/plugin/examples/RedBlack/redblack.v
58-275:  (../../../pub/plugin/examples/RedBlack/redblack.v) [3]
58-275: (../../../pub/plugin/examples/RedBlack/testing.v)
58-275: (../../../pub/plugin/examples/RedBlack/testing.v)
58-275: (../../../pub/plugin/examples/RedBlack/testing.v)
58-275: (../../../pub/plugin/examples/RedBlack/testing.v) [4]
58-275: (../../../pub/plugin/examples/RedBlack/testing.v)
58-275: (../../../pub/plugin/examples/RedBlack/testing.v)
58-275: (../../../pub/plugin/examples/RedBlack/testing.v) [5]
58-275: (../../../pub/plugin/examples/RedBlack/verif.v)
58-275: (../../../pub/plugin/src/SemChecker.v)
574-271: (../../../pub/plugin/src/SemChecker.v) (../../../pub/plugin/src/SemChecker.v)
574-271: (../../../pub/plugin/examples/RedBlack/verif.v)
574-271: (../../../pub/plugin/examples/RedBlack/verif.v)
574-271: (../../../pub/plugin/examples/RedBlack/verif.v)
574-271: (../../../pub/plugin/examples/RedBlack/verif.v)
574-271: (../../../pub/plugin/src/GenLow.v) (../../../pub/plugin/src/GenLow.v)
626-331: (../../../pub/plugin/src/GenHigh.v) (../../../pub/plugin/src/GenHigh.v)
626-331: (../../../pub/plugin/src/GenHigh.v [6]) (../../../pub/plugin/src/GenLow.v)
691-43:  (../../../pub/plugin/src/GenLow.v) [8]
691-43: (../../../pub/plugin/src/SemChecker.v) (../../../pub/plugin/src/SemChecker.v)
691-43: (../../../pub/plugin/src/SemChecker.v) (../../../pub/plugin/src/SemChecker.v)
934-1030: (../../../pub/plugin/src/Random.v) [9]
1030-1030: LaTeX warning: Reference `tab:lib' on page 10 undefined on input line 1030.
1030-1735: (../../../pub/plugin/src/SemChecker.v [10]) (../../../pub/plugin/src/Random.v)
1030-1735: (../../../pub/plugin/src/CoArbitrary.v) [11] [12] [13] [14] (./main.bbl

**Comment by dmwit** [comment]
Ugh, annoying. Well, as a nasty workaround, you could add something like `& !"\(\.\./\.\./\.\./pub/plugin/src/.*\.v"`. I agree this is only a temporary solution, though.

**Comment by dmwit** [comment]
This should be fixed. Can I include your log as a regression test?

**Comment by catalin-hritcu** [comment]
Sure. I don't see any new commit though.

**Comment by dmwit** [comment]
Sorry about that. I'm traveling, and having trouble pushing over this network connection. I should be back Sunday night, and should be able to push no later than Monday.

**Comment by dmwit** [comment]
(pushed)
